### ISSUE TITLE
setVolumeLevel on iOS

### ISSUE THREAD

**Issue by co-dax** [ottimis/capacitor-volumes#2]
At the following page [https://github.com/ottimis/capacitor-volumes?tab=readme-ov-file#setvolumelevel](https://github.com/ottimis/capacitor-volumes?tab=readme-ov-file#setvolumelevel) is states that setVolumeLevel(...) does not work on iOS but it does work on iOS.

**Comment by mmoriani** [comment]
Hello, thanks for your message.

As stated here: https://developer.apple.com/documentation/avfaudio/avaudiosession/1616533-outputvolume, Apple specifies: _“Only the user can directly set the system volume.”_

This means no plugins can set the volume programmatically.

**Comment by co-dax** [comment]
I understand but I can also confirm that Volumes.setVolumeLevel(...) does set the system volume programatically on iOS :-)
I can also notice the volume bar appearing on iOS display and being automatically set to the specified values.

It is essentially working better than it is supposed to.
